version: '3.8'

services:
  codeyx-backend-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeyx-backend-aggregator
    ports:
      - "5005:5005"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
