const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '..', '.env') });

const MasterProblemSchema = new mongoose.Schema(
  {
    problemId: { type: Number, required: true },
    title: { type: String, required: true },
    platform: { type: String, default: '' },
    link: { type: String, default: '' },
    links: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { strict: false }
);

const MasterProblem = mongoose.models.MasterProblem || mongoose.model('MasterProblem', MasterProblemSchema);

const PLATFORM_URLS = {
  leetcode: (title) => {
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
    return `https://leetcode.com/problems/${slug}/`;
  },
  geeksforgeeks: (title) => {
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
    return `https://www.geeksforgeeks.org/${slug}/`;
  },
  neetcode: (title) => {
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
    return `https://neetcode.io/problems/${slug}`;
  },
  interviewbit: (title) => {
    const slug = title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    return `https://www.interviewbit.com/problems/${slug}/`;
  },
};

async function run() {
  const mongoUri = process.env.MONGODB_URI;
  if (!mongoUri) {
    console.error('MONGODB_URI not found in .env');
    process.exit(1);
  }

  console.log('Connecting to MongoDB...');
  await mongoose.connect(mongoUri);
  console.log('Connected!');

  const problems = await MasterProblem.find({}).lean();
  console.log(`Auditing ${problems.length} master problems...`);

  let cleanedCount = 0;

  for (const prob of problems) {
    const title = prob.title || '';
    const platform = (prob.platform || '').toLowerCase();
    const links = { ...(prob.links || {}) };
    let changed = false;

    // Check each platform key in links
    for (const key of ['leetcode', 'geeksforgeeks', 'neetcode', 'interviewbit']) {
      if (links[key]) {
        // If it matches the auto-generated formula AND is not the primary platform, delete it!
        const autoUrl = PLATFORM_URLS[key](title);
        const currentUrl = links[key];
        
        const isAutoGenerated = currentUrl.toLowerCase().trim() === autoUrl.toLowerCase().trim();
        const isPrimary = platform === key || (key === 'geeksforgeeks' && platform === 'gfg') || (key === 'codingninjas' && (platform === 'codestudio' || platform === 'code360'));

        if (isAutoGenerated && !isPrimary) {
          console.log(`[Clean] Removing ${key} link from "${title}" (Primary: ${platform})`);
          delete links[key];
          changed = true;
        }
      }
    }

    if (changed) {
      await MasterProblem.updateOne(
        { _id: prob._id },
        { $set: { links } }
      );
      cleanedCount++;
    }
  }

  console.log(`\n🎉 Successfully cleaned up ${cleanedCount} master problems!`);
  await mongoose.disconnect();
  console.log('Disconnected.');
}

run().catch(console.error);
