export const DEGREE_OPTIONS = [
  { id: 'btech', label: 'B.Tech / B.E.', aliases: ['btech', 'b.tech', 'b e', 'b.e.', 'bachelor of technology', 'bachelor of engineering'] },
  { id: 'bca', label: 'BCA', aliases: ['bachelor of computer applications'] },
  { id: 'bsc', label: 'B.Sc Computer Science', aliases: ['bsc cs', 'b.sc', 'bachelor of science'] },
  { id: 'mtech', label: 'M.Tech / M.E.', aliases: ['mtech', 'm.tech', 'm.e.', 'master of technology', 'master of engineering'] },
  { id: 'mca', label: 'MCA', aliases: ['master of computer applications'] },
  { id: 'mba', label: 'MBA', aliases: ['master of business administration'] },
  { id: 'msc', label: 'M.Sc', aliases: ['msc cs', 'master of science'] },
  { id: 'phd', label: 'PhD', aliases: ['doctor of philosophy', 'doctorate'] },
  { id: 'diploma', label: 'Polytechnic Diploma', aliases: ['diploma in computer', 'polytechnic'] },
];

export const BRANCH_OPTIONS = [
  { id: 'cse', label: 'Computer Science', aliases: ['cs', 'comp sci'] },
  { id: 'cse_eng', label: 'Computer Science Engineering', aliases: ['cse', 'cs engineering'] },
  { id: 'cse_amp', label: 'Computer Science & Engineering', aliases: ['cse'] },
  { id: 'it', label: 'Information Technology', aliases: ['it', 'info tech'] },
  { id: 'se', label: 'Software Engineering', aliases: ['swe', 'software'] },
  { id: 'ai', label: 'Artificial Intelligence', aliases: ['ai'] },
  { id: 'aiml', label: 'Artificial Intelligence & Machine Learning', aliases: ['ai ml', 'aiml'] },
  { id: 'ml', label: 'Machine Learning', aliases: ['ml'] },
  { id: 'ds', label: 'Data Science', aliases: ['ds', 'data analytics'] },
  { id: 'cyber', label: 'Cyber Security', aliases: ['cyber', 'infosec'] },
  { id: 'cloud', label: 'Cloud Computing', aliases: ['cloud'] },
  { id: 'blockchain', label: 'Blockchain Technology', aliases: ['blockchain', 'crypto'] },
  { id: 'iot', label: 'Internet of Things', aliases: ['iot'] },
  { id: 'fsd', label: 'Full Stack Development', aliases: ['full stack'] },
  { id: 'webdev', label: 'Web Development', aliases: ['web dev'] },
  { id: 'mobile', label: 'Mobile App Development', aliases: ['app dev', 'android', 'ios'] },
  { id: 'devops', label: 'DevOps', aliases: ['devops'] },
  { id: 'cloud_eng', label: 'Cloud Engineering', aliases: ['cloud eng'] },
  { id: 'sre', label: 'Site Reliability Engineering', aliases: ['sre'] },
  { id: 'network', label: 'Computer Networking', aliases: ['networking'] },
  { id: 'net_sec', label: 'Network Security', aliases: ['net sec'] },
  { id: 'info_sec', label: 'Information Security', aliases: ['infosec'] },
  { id: 'ethical', label: 'Ethical Hacking', aliases: ['hacking', 'pentesting'] },
  { id: 'big_data', label: 'Big Data Analytics', aliases: ['big data'] },
  { id: 'business_analytics', label: 'Business Analytics', aliases: ['ba'] },
  { id: 'embedded', label: 'Embedded Systems', aliases: ['embedded'] },
  { id: 'vlsi', label: 'VLSI Design', aliases: ['vlsi'] },
  { id: 'robotics', label: 'Robotics Engineering', aliases: ['robotics'] },
  { id: 'automation', label: 'Automation Engineering', aliases: ['automation'] },
  { id: 'ece', label: 'Electronics & Communication', aliases: ['ece', 'electronics'] },
  { id: 'ee', label: 'Electrical Engineering', aliases: ['ee', 'electrical'] },
  { id: 'eee', label: 'Electrical & Electronics Engineering', aliases: ['eee'] },
  { id: 'me', label: 'Mechanical Engineering', aliases: ['mech', 'me'] },
  { id: 'ce', label: 'Civil Engineering', aliases: ['civil', 'ce'] },
  { id: 'che', label: 'Chemical Engineering', aliases: ['chem'] },
  { id: 'bio', label: 'Biotechnology', aliases: ['biotech'] },
  { id: 'biomedical', label: 'Biomedical Engineering', aliases: ['biomedical'] },
  { id: 'aero', label: 'Aerospace Engineering', aliases: ['aerospace'] },
  { id: 'aeronautical', label: 'Aeronautical Engineering', aliases: ['aeronautical'] },
  { id: 'auto', label: 'Automobile Engineering', aliases: ['automobile'] },
  { id: 'industrial', label: 'Industrial Engineering', aliases: ['industrial'] },
  { id: 'production', label: 'Production Engineering', aliases: ['production'] },
  { id: 'mining', label: 'Mining Engineering', aliases: ['mining'] },
  { id: 'petroleum', label: 'Petroleum Engineering', aliases: ['petroleum'] },
  { id: 'agri', label: 'Agricultural Engineering', aliases: ['agriculture'] },
  { id: 'env', label: 'Environmental Engineering', aliases: ['environmental'] },
  { id: 'textile', label: 'Textile Engineering', aliases: ['textile'] },
  { id: 'food', label: 'Food Technology', aliases: ['food tech'] },
  { id: 'instrumentation', label: 'Instrumentation Engineering', aliases: ['instrumentation'] },
  { id: 'mechatronics', label: 'Mechatronics Engineering', aliases: ['mechatronics'] },
  { id: 'structural', label: 'Structural Engineering', aliases: ['structural'] },
  { id: 'construction', label: 'Construction Engineering', aliases: ['construction'] },
  { id: 'game_dev', label: 'Game Development', aliases: ['gaming'] },
  { id: 'arvr', label: 'AR/VR Engineering', aliases: ['ar', 'vr', 'virtual reality'] },
  { id: 'uiux', label: 'UI/UX Design', aliases: ['ui', 'ux', 'design'] },
  { id: 'hci', label: 'Human Computer Interaction', aliases: ['hci'] },
  { id: 'quantum', label: 'Quantum Computing', aliases: ['quantum'] },
  { id: 'computational_sci', label: 'Computational Science', aliases: ['comp sci'] },
  { id: 'digital_sys', label: 'Digital Systems', aliases: ['digital'] },
  { id: 'multimedia', label: 'Multimedia Technology', aliases: ['multimedia'] },
  { id: 'animation', label: 'Animation & Gaming', aliases: ['animation'] },
  { id: 'forensics', label: 'Digital Forensics', aliases: ['forensics'] },
  { id: 'bioinformatics', label: 'Bioinformatics', aliases: ['bioinformatics'] },
  { id: 'comp_bio', label: 'Computational Biology', aliases: ['comp bio'] },
  { id: 'enterprise', label: 'Enterprise Systems', aliases: ['enterprise'] },
  { id: 'distributed', label: 'Distributed Systems', aliases: ['distributed'] },
  { id: 'parallel', label: 'Parallel Computing', aliases: ['parallel'] },
  { id: 'hpc', label: 'High Performance Computing', aliases: ['hpc'] },
  { id: 'edge', label: 'Edge Computing', aliases: ['edge'] },
  { id: 'fintech', label: 'FinTech Engineering', aliases: ['fintech'] },
  { id: 'healthtech', label: 'HealthTech Engineering', aliases: ['healthtech'] },
  { id: 'edtech', label: 'EdTech Systems', aliases: ['edtech'] },
  { id: 'ecommerce', label: 'E-Commerce Technology', aliases: ['e-commerce'] },
  { id: 'smart_sys', label: 'Smart Systems Engineering', aliases: ['smart sys'] },
  { id: 'intelligent', label: 'Intelligent Systems', aliases: ['intelligent'] },
];

export const JOB_ROLE_OPTIONS = [
  { id: 'sde', label: 'SDE / Software Engineer', aliases: ['sde', 'swe', 'software engineer'] },
  { id: 'frontend', label: 'Frontend Developer', aliases: ['front end', 'frontend', 'ui developer'] },
  { id: 'backend', label: 'Backend Developer', aliases: ['back end', 'backend', 'api developer'] },
  { id: 'fullstack', label: 'Full Stack Developer', aliases: ['fullstack', 'full stack'] },
  { id: 'swe_dev', label: 'Software Development Engineer', aliases: ['swe'] },
  { id: 'webdev', label: 'Web Developer', aliases: ['web dev'] },
  { id: 'mobile', label: 'Mobile App Developer', aliases: ['mobile dev'] },
  { id: 'android', label: 'Android Developer', aliases: ['android'] },
  { id: 'ios', label: 'iOS Developer', aliases: ['ios', 'swift'] },
  { id: 'react', label: 'React Developer', aliases: ['react', 'reactjs'] },
  { id: 'nextjs', label: 'Next.js Developer', aliases: ['nextjs', 'next.js'] },
  { id: 'nodejs', label: 'Node.js Developer', aliases: ['node', 'nodejs'] },
  { id: 'java', label: 'Java Developer', aliases: ['java'] },
  { id: 'python', label: 'Python Developer', aliases: ['python'] },
  { id: 'cpp', label: 'C++ Developer', aliases: ['cpp', 'c++'] },
  { id: 'go', label: 'Go Developer', aliases: ['golang', 'go'] },
  { id: 'rust', label: 'Rust Developer', aliases: ['rust'] },
  { id: 'ai_eng', label: 'AI Engineer', aliases: ['ai', 'artificial intelligence'] },
  { id: 'ml_eng', label: 'Machine Learning Engineer', aliases: ['ml', 'machine learning'] },
  { id: 'dl_eng', label: 'Deep Learning Engineer', aliases: ['dl', 'deep learning'] },
  { id: 'data_sci', label: 'Data Scientist', aliases: ['data science'] },
  { id: 'data_ana', label: 'Data Analyst', aliases: ['data analytics'] },
  { id: 'data_eng', label: 'Data Engineer', aliases: ['data eng'] },
  { id: 'cloud', label: 'Cloud Engineer', aliases: ['cloud', 'aws', 'gcp', 'azure'] },
  { id: 'devops', label: 'DevOps Engineer', aliases: ['devops'] },
  { id: 'sre', label: 'Site Reliability Engineer (SRE)', aliases: ['sre'] },
  { id: 'cyber', label: 'Cyber Security Engineer', aliases: ['cyber security', 'infosec', 'pentester'] },
  { id: 'blockchain', label: 'Blockchain Developer', aliases: ['web3', 'crypto', 'smart contract'] },
  { id: 'game', label: 'Game Developer', aliases: ['unity', 'unreal', 'gaming'] },
  { id: 'arvr', label: 'AR/VR Developer', aliases: ['ar', 'vr', 'mixed reality'] },
  { id: 'ui_eng', label: 'UI Engineer', aliases: ['ui'] },
  { id: 'ux_eng', label: 'UX Engineer', aliases: ['ux'] },
  { id: 'uiux_des', label: 'UI/UX Designer', aliases: ['designer', 'uiux'] },
  { id: 'product_eng', label: 'Product Engineer', aliases: ['product'] },
  { id: 'qa', label: 'QA Engineer', aliases: ['qa', 'tester', 'quality assurance'] },
  { id: 'auto_test', label: 'Automation Test Engineer', aliases: ['sdet', 'automation'] },
  { id: 'embedded', label: 'Embedded Systems Engineer', aliases: ['embedded'] },
  { id: 'vlsi', label: 'VLSI Engineer', aliases: ['vlsi'] },
  { id: 'robotics', label: 'Robotics Engineer', aliases: ['robotics'] },
  { id: 'iot', label: 'IoT Engineer', aliases: ['iot'] },
  { id: 'dba', label: 'Database Administrator', aliases: ['dba', 'database'] },
  { id: 'solutions_arch', label: 'Solutions Architect', aliases: ['architect', 'solutions'] },
  { id: 'system_eng', label: 'System Engineer', aliases: ['systems'] },
  { id: 'platform_eng', label: 'Platform Engineer', aliases: ['platform'] },
  { id: 'open_source', label: 'Open Source Contributor', aliases: ['oss', 'open source'] },
  { id: 'research', label: 'Research Engineer', aliases: ['researcher', 'r&d'] },
  { id: 'cp', label: 'Competitive Programmer', aliases: ['cp', 'sport programmer'] },
  { id: 'tech_lead', label: 'Tech Lead', aliases: ['lead'] },
  { id: 'em', label: 'Engineering Manager', aliases: ['em', 'manager'] },
  { id: 'founder', label: 'Startup Founder', aliases: ['founder', 'entrepreneur'] },
  { id: 'freelancer', label: 'Freelancer', aliases: ['freelance'] },
];

export const COUNTRY_OPTIONS = [
  { id: 'in', label: 'India', aliases: ['ind'] },
  { id: 'us', label: 'United States', aliases: ['usa', 'america', 'us'] },
  { id: 'ca', label: 'Canada', aliases: ['can'] },
  { id: 'uk', label: 'United Kingdom', aliases: ['uk', 'britain', 'england'] },
  { id: 'de', label: 'Germany', aliases: ['ger', 'deutschland'] },
  { id: 'au', label: 'Australia', aliases: ['aus'] },
  { id: 'sg', label: 'Singapore', aliases: ['sg'] },
  { id: 'ae', label: 'United Arab Emirates', aliases: ['uae', 'dubai'] },
  { id: 'jp', label: 'Japan', aliases: ['jpn'] },
  { id: 'kr', label: 'South Korea', aliases: ['korea', 'kr'] },
  { id: 'fr', label: 'France', aliases: ['fr'] },
  { id: 'nl', label: 'Netherlands', aliases: ['holland', 'nl'] },
  { id: 'se', label: 'Sweden', aliases: ['swe'] },
  { id: 'ch', label: 'Switzerland', aliases: ['swiss', 'ch'] },
  { id: 'ie', label: 'Ireland', aliases: ['ie'] },
  { id: 'nz', label: 'New Zealand', aliases: ['nz'] },
  { id: 'cn', label: 'China', aliases: ['cn', 'prc'] },
  { id: 'ru', label: 'Russia', aliases: ['ru'] },
  { id: 'br', label: 'Brazil', aliases: ['br'] },
  { id: 'it', label: 'Italy', aliases: ['it'] },
  { id: 'es', label: 'Spain', aliases: ['es', 'espana'] },
  { id: 'pl', label: 'Poland', aliases: ['pl'] },
  { id: 'no', label: 'Norway', aliases: ['no'] },
  { id: 'fi', label: 'Finland', aliases: ['fi'] },
  { id: 'dk', label: 'Denmark', aliases: ['dk'] },
  { id: 'be', label: 'Belgium', aliases: ['be'] },
  { id: 'at', label: 'Austria', aliases: ['at'] },
  { id: 'my', label: 'Malaysia', aliases: ['my'] },
  { id: 'id', label: 'Indonesia', aliases: ['id'] },
  { id: 'th', label: 'Thailand', aliases: ['th'] },
  { id: 'vn', label: 'Vietnam', aliases: ['vn'] },
  { id: 'ph', label: 'Philippines', aliases: ['ph'] },
  { id: 'pk', label: 'Pakistan', aliases: ['pk', 'pak'] },
  { id: 'bd', label: 'Bangladesh', aliases: ['bd'] },
  { id: 'np', label: 'Nepal', aliases: ['np'] },
  { id: 'lk', label: 'Sri Lanka', aliases: ['lk'] },
  { id: 'za', label: 'South Africa', aliases: ['za', 'rsa'] },
  { id: 'mx', label: 'Mexico', aliases: ['mx'] },
  { id: 'tr', label: 'Turkey', aliases: ['tr', 'turkiye'] },
  { id: 'sa', label: 'Saudi Arabia', aliases: ['sa', 'ksa'] },
  { id: 'qa', label: 'Qatar', aliases: ['qa'] },
  { id: 'kw', label: 'Kuwait', aliases: ['kw'] },
  { id: 'om', label: 'Oman', aliases: ['om'] },
  { id: 'eg', label: 'Egypt', aliases: ['eg'] },
  { id: 'il', label: 'Israel', aliases: ['il'] },
];

// Generate years dynamically
export const getGradYearOptions = () => {
  const currentYear = new Date().getFullYear();
  const years = [];
  for (let y = currentYear - 10; y <= currentYear + 10; y++) {
    years.push({ id: String(y), label: String(y), aliases: [] });
  }
  return years;
};
